PACT-871 : Modify request and response for creators to match new API schema
nationalarchives/ctd-omega-editorial-frontend pull request #118
Opened 2023-05-26 14:25 UTC by userjd

2023-05-30 08:59 UTC, rwalpole requested changes
We are missing a test for `getAgentSummaries` in `MessagingServiceSpec`. In fact there should be at least two - one for the happy path and one where the reply message cannot be parsed.

2023-05-30 08:59 UTC, rwalpole commented on app/uk/gov/nationalarchives/omega/editorial/models/AgentSummary.scala
> +      case (_, None, None)                                         => ""
`case _ => ""` might be better here.

2023-05-30 08:59 UTC, rwalpole commented on app/uk/gov/nationalarchives/omega/editorial/models/AgentSummary.scala
> +  val displayedName = {
Missing type annotation.

2023-05-30 11:05 UTC, userjd commented on app/uk/gov/nationalarchives/omega/editorial/models/AgentSummary.scala
> +      case (_, None, None)                                         => ""
Done

2023-05-30 11:05 UTC, userjd commented on app/uk/gov/nationalarchives/omega/editorial/models/AgentSummary.scala
> +  val displayedName = {
Done

2023-06-05 11:44 UTC, rwalpole approved these changes

2023-06-05 11:44 UTC, merged